FROM alpine:latest

copy-from-rel:
    COPY ./subdir+whoami/whoami .
    RUN cat whoami

copy-from-trusted-remote:
    COPY --allow-privileged github.com/alexcb/locally/tests/subdir:main+whoami2/whoami .
    RUN cat whoami

all:
    #BUILD +copy-from-rel
    BUILD +copy-from-trusted-remote
